server:
  port: 8001
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8000/eureka/
spring:
  application:
    name: oauth2-server
logging:
  level:
    root: info
